let jobList = [
  {
    id: 1,
    company: "Mobile First Corp",
    role: "React Native Developer",
    location: "Remote",
    type: "Full-time",
    salary: "$100k - $115k",
    description: "Build cross-platform mobile applications.",
    applicationStatus: "All",
  },
  {
    id: 2,
    company: "WebFlow Agency",
    role: "Web Designer & Developer",
    location: "Los Angeles, CA",
    type: "Part-time",
    salary: "$80k - $100k",
    description: "Create stunning web experiences.",
    applicationStatus: "All",
  },
  {
    id: 3,
    company: "DataViz Solutions",
    role: "Data Visualization Specialist",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$110k - $130k",
    description: "Transform complex data into visualizations.",
    applicationStatus: "All",
  },
  {
    id: 4,
    company: "CloudFirst Inc",
    role: "Backend Developer",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$140k - $160k",
    description: "Design scalable backend systems.",
    applicationStatus: "All",
  },
  {
    id: 5,
    company: "Innovation Labs",
    role: "UI/UX Engineer",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$110k - $130k",
    description: "Create beautiful user interfaces.",
    applicationStatus: "All",
  },
  {
    id: 6,
    company: "MegaCorp Solutions",
    role: "JavaScript Developer",
    location: "New York, NY",
    type: "Full-time",
    salary: "$130k - $150k",
    description: "Build enterprise applications.",
    applicationStatus: "All",
  },
  {
    id: 7,
    company: "StartupXYZ",
    role: "Full Stack Engineer",
    location: "Remote",
    type: "Full-time",
    salary: "$140k - $160k",
    description: "Join our fast-growing startup.",
    applicationStatus: "All",
  },
  {
    id: 8,
    company: "TechCorp Industries",
    role: "Senior Frontend Developer",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$150k - $175k",
    description: "Build reliable web applications.",
    applicationStatus: "All",
  },
];


let activeTab="All";
